// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramTest.Data;

#nullable disable

namespace ProgramTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramTest.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nama")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("tblM_Gender");
                });

            modelBuilder.Entity("ProgramTest.Models.Hobi", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)");

                    b.Property<string>("Nama")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("tblM_Hobi");
                });

            modelBuilder.Entity("ProgramTest.Models.Personal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdGender")
                        .HasColumnType("int");

                    b.Property<string>("IdHobi")
                        .HasColumnType("char(1)");

                    b.Property<string>("Nama")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Umur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGender");

                    b.HasIndex("IdHobi");

                    b.ToTable("tblT_Personal");
                });

            modelBuilder.Entity("ProgramTest.Models.Umur", b =>
                {
                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("Total")
                        .HasColumnType("int");

                    b.ToTable("tblT_Umur");
                });

            modelBuilder.Entity("ProgramTest.Models.Personal", b =>
                {
                    b.HasOne("ProgramTest.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("IdGender");

                    b.HasOne("ProgramTest.Models.Hobi", "Hobi")
                        .WithMany()
                        .HasForeignKey("IdHobi");

                    b.Navigation("Gender");

                    b.Navigation("Hobi");
                });
#pragma warning restore 612, 618
        }
    }
}
